// console.log(document.title)
// console.log(document.URL)
// console.log(document.head)
// console.log(document.body)

// var a=document.getElementById("heading")
// console.log(a)

// var a=document.getElementsByName('check')
// console.log(a)
// var a=document.getElementsByTagName('')

// var a=document.querySelector('#head')
// console.log(a)

// var a=document.querySelectorAll('p')
// console.log(a)

// function add(...a){ 
//         total=0
//         for (const sum of a) {
//             total +=sum
//         } 
// console.log(total)
// }
// add(1,2,4,4,5 ,4 ,32,6,8,71,90,48,7,9)


// function fun(a,b,...c){
//     console.log(`${a} ${b}`);
//     console.log(c);
//     console.log(c[0]);
//     console.log(c.length);
// }
// fun('allen','martin','king','james','scott')
