// let x = 10
// let y =0
// let result = "IKI"


// if (y = 20)
// {
//       result = y/x

//  console.log(result)
// }



// if (y > 0 )
// {
//      console.log("Y is positive")
// }
// else if  (y == 0 )
// {
//      console.log("Y is Neutral")
//  }
//  else {
//      console.log("Y is Negative")
// }

// let no_of_wheels = 1
// month = 11
// /switch(no_of_wheels)
//  {

// if (no_of_wheels == 1 )
//  {
//          console.log("Its just a wheel")
//     no_of_wheels = 2
//  }
//  else if (no_of_wheels == 2)
//  {
//      console.log("Its a Bike")
//  }
// else if (no_of_wheels == 3)
//  {
//      console.log("Its an Auto")
//  }
//  else if (no_of_wheels == 4)
// {
//     console.log("Its a Car")
// }
//  else{
//     console.log("Its a Big Vehicle")
// }
// }
//     switch(month)
//  {

// case 1:
//              console.log("Its just a wheel")
//                 break
//      case 2:
//                 console.log("Its a bike")
//                break
//         case 3:
//                  console.log("Its auto")
//             break
//                  case 4:
//                 console.log("Its Car")
//                 break
//         case 5:
//                 console.log("Its Jeep")
//                  break
//          case 6:
//              console.log("Its Truck")
//                 break
//         default:
//               console.log("Enter valid Input!!")
// }



// const marks = parseFloat(prompt("Enter the student's marks:"));

//     if (marks >= 80 && marks <= 100) {
//        console.log( "Distinction");
//     } else if (marks >= 60 && marks < 80) {
//         console.log( "First class");
//     } else if (marks >= 50 && marks < 60) {
//         console.log( "second class");
//     } else if (marks >= 35 && marks < 50) {
//         console.log( "passs");
//     } else if (marks >= 0 && marks < 35) {
//         console.log( "fail");
//     } else {
//         console.log( "invalid");
//     }



// const userage=prompt("Enter your age: ");
// if(userage>=18){

//     console.log(`u r ${userage} eligible for vote:`)
// }else{
//     const ytv=18-userage;
//     console.log(`you are under age plz wait for ${ytv} year to  vote `)
// }

// let a=10
// console.log(a)

// const hours=parseInt(prompt("enter the hour"));
//     if(hours>=6 && hours<=12){
//        console.log("good morning")

//     }
//     else if(hours>=12 && hours<18){
//         console.log("good afternoon")
 
//      }
//      else if (hours>=18 && hours<24)
//      {
//         console.log("good night")
 
//      }
//      else{
//         console.log("go and sleep")
//      }
 

 
// let a=Array (4 ,'dd')
// let arr3 ='12345'.split('')
// console.log(arr3,a)

// let FrontEnd = ["HTML", "CSS", "Javascript", "React", "MongoDB"]

// console.log(FrontEnd[4])
// console.log(FrontEnd.length)
// console.log(FrontEnd[FrontEnd.length-1])
// console.log(FrontEnd[50])

// FrontEnd[4] = "Angular"
// console.log(FrontEnd)


// let str1 = "Angular"
// console.log(str1[3])

// str1[4] = "Xdgsg"
// console.log(str1)

// console.log(FrontEnd.length)

// FrontEnd[80] = "VueJS"

// console.log(FrontEnd.length)


// let arr10 = Array(5).fill("")
// let arr11 = [1,2,4,5].fill(3 ,4)

// console.log(FrontEnd.indexOf('VueJS'))

// console.log(FrontEnd.toString())
// console.log(FrontEnd.join())
// console.log(FrontEnd.join(' '))


// let new_array1 = FrontEnd.slice(1,4)
// console.log(new_array1)
// console.log("new_array1 ==> ", new_array1)


// console.log(FrontEnd)
// FrontEnd.reverse()
// FrontEnd.sort()
// console.log("After ==> ", FrontEnd)

// var array=[1,'India',100,'pak','nw',300]
// console.log(array)
// array.push()


// var array=[1,'India',100,'pak','nw',300]
// (array.pop()

// var array=[1,'India',100,'pak','nw',300]
// console.log(array.unshift('r'))

// var array=[1,'India',100,'pak','nw',300]
// console.log(array.shift())

// var array=[1,'India',100,'pak','nw',300]
// console.log(array.reverse())
// var array=[1,'India',100,'pak','nw',300]
// console.log(array.sort())

// var array=[1,'India',100,'pak','nw',300]
// console.log(array.slice(1,3))


// //[india,pak,nw,1,100,300]
//  = [1, 2, 3];

// const doubledNumbers = numbers.map(number => number * 2);

// console.log(doubledNumbers); // [2, 4, 6]


// const numbers = [1, 2, 3];

// const numbers
// let num=numbers.forEach(number => (number*2));
// console.log(num)
